# Usar la base image de Alpine para Apache
FROM docker.io/library/httpd:alpine

# Cambiar el port de escucha del 80 (requiere root) al 8080
RUN sed -i "s/Listen 80/Listen 8080/g" /usr/local/apache2/conf/httpd.conf

# Crear el archivo index.html con el texto "hola" en el DocumentRoot de Alpine
RUN echo "hola" > /usr/local/apache2/htdocs/index.html

# Modificar permisos para la compatibilidad con OpenShift
# OpenShift ejecuta contenedores con un UID aleatorio, pero siempre con el GID 0.
RUN chgrp -R 0 /usr/local/apache2/ && \
    chmod -R g=u /usr/local/apache2/

# Exponer el port 8080
EXPOSE 8080

# Establecer un non-root user por defecto
# OpenShift ignorará este número y asignará uno propio, pero es buena práctica tenerlo para entornos locales
USER 1001