apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: anyuid-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-anyuid-scc
  namespace: cicd-renato
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: anyuid-sa
  namespace: cicd-renato
---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: my-app
  template:
    metadata:
      labels:
        deployment: my-app
    spec:
      serviceAccount: anyuid-sa
      containers:
      - image: kennethreitz/httpbin:latest
        imagePullPolicy: IfNotPresent
        name: my-app
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  ports:
  - name: 80-tcp
    port: 80
  selector:
    deployment: my-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  host: ''
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: my-app
    weight: 100
  wildcardPolicy: None